import { existsSync, readFileSync } from 'node:fs';
import { ClaudeJsonSchema, type OauthAccount } from './schema.js';
import { writeJsonAtomic } from './fs-safe.js';
import { writeProfile } from './profile.js';
import { AUTH_KEYS, checkTokenPrefix } from './scheme.js';
import type { Paths } from './paths.js';

export interface InitInput {
  token: string;
  account: OauthAccount;
  profileName?: string;
  lastOnboardingVersion?: string;
}

export interface InitResult {
  claudeJsonPath: string;
  profileName: string;
}

export function readLocalOauthAccount(paths: Paths): OauthAccount | null {
  if (!existsSync(paths.claudeJson)) return null;
  try {
    const raw = JSON.parse(readFileSync(paths.claudeJson, 'utf8'));
    const parsed = ClaudeJsonSchema.safeParse(raw);
    if (!parsed.success) return null;
    return parsed.data.oauthAccount ?? null;
  } catch {
    return null;
  }
}

export function performInit(paths: Paths, input: InitInput): InitResult {
  // Validate token prefix (warn but allow if user wants — caller can pre-check)
  const pre = checkTokenPrefix(AUTH_KEYS.OAUTH, input.token);
  if (!pre.ok) {
    throw new Error(
      `OAuth token must start with '${pre.expected}'. Pass --force to override.`,
    );
  }

  const claudeJson = {
    hasCompletedOnboarding: true,
    lastOnboardingVersion: input.lastOnboardingVersion ?? '2.1.29',
    oauthAccount: input.account,
  };
  writeJsonAtomic(paths.claudeJson, claudeJson, { mode: 0o600 });

  const profileName = input.profileName ?? 'oauth';
  writeProfile(paths, profileName, {
    env: { [AUTH_KEYS.OAUTH]: input.token },
    meta: {
      description: 'Created by claude-switch init',
    },
  });

  return { claudeJsonPath: paths.claudeJson, profileName };
}

export function buildBashScript(input: InitInput): string {
  const account = JSON.stringify({
    hasCompletedOnboarding: true,
    lastOnboardingVersion: input.lastOnboardingVersion ?? '2.1.29',
    oauthAccount: input.account,
  });
  return `#!/usr/bin/env bash
# Generated by claude-switch init --print-script
set -euo pipefail

# 1. Export OAuth token (subscription-based)
grep -q CLAUDE_CODE_OAUTH_TOKEN ~/.bashrc.local 2>/dev/null || \\
  echo 'export CLAUDE_CODE_OAUTH_TOKEN="${input.token}"' >> ~/.bashrc.local
chmod 600 ~/.bashrc.local

# 2. Bypass onboarding wizard
cat > ~/.claude.json <<'JSON'
${account}
JSON
chmod 600 ~/.claude.json

# 3. Make sure ~/.bashrc sources ~/.bashrc.local
grep -q '.bashrc.local' ~/.bashrc 2>/dev/null || \\
  echo '[[ -f ~/.bashrc.local ]] && . ~/.bashrc.local' >> ~/.bashrc

echo "Done. Open a new shell or: source ~/.bashrc"
`;
}

export function buildAnsibleSnippet(input: InitInput): string {
  return `# Generated by claude-switch init --ansible
- name: Configure Claude Code OAuth token in bashrc.local
  copy:
    content: |
      # Claude Code OAuth token (managed by Ansible)
      export CLAUDE_CODE_OAUTH_TOKEN="${input.token}"
    dest: "/home/{{ target_user }}/.bashrc.local"
    owner: "{{ target_user }}"
    mode: '0600'
  no_log: true

- name: Configure Claude Code onboarding bypass
  copy:
    content: |
      {
        "hasCompletedOnboarding": true,
        "lastOnboardingVersion": "${input.lastOnboardingVersion ?? '2.1.29'}",
        "oauthAccount": {
          "accountUuid": "${input.account.accountUuid}",
          "emailAddress": "${input.account.emailAddress}",
          "organizationUuid": "${input.account.organizationUuid}"
        }
      }
    dest: "/home/{{ target_user }}/.claude.json"
    owner: "{{ target_user }}"
    mode: '0600'
`;
}
